/*
    Name:           [dbo].[uspSeed_Artist]
    Author:         Chris Pickford
    Created:        2016-01-21
    Description:    Populates table with seed data to be executed post-deployment.
                    Use the following SQL to generate values from a populated table:
                        SELECT N'('
                            +  ISNULL('N''' + REPLACE(CONVERT(NVARCHAR(MAX), [Name]			), '''', '''''') + '''', 'NULL') + ', '
                            +  ISNULL('N''' + REPLACE(CONVERT(NVARCHAR(MAX), [Biography]	), '''', '''''') + '''', 'NULL') + ', '
                            +  ISNULL('N''' + REPLACE(CONVERT(NVARCHAR(MAX), [WebsiteURL]	), '''', '''''') + '''', 'NULL') + ', '
                            +  ISNULL(                CONVERT(NVARCHAR(MAX), [StartYear]	)                      , 'NULL') + ', '
                            +  ISNULL(                CONVERT(NVARCHAR(MAX), [EndYear]		)                      , 'NULL')
                            + N'),'
                        FROM [dbo].[Artist];
*/
CREATE PROCEDURE [dbo].[uspSeed_Artist]
AS

SET NOCOUNT ON;

MERGE INTO [dbo].[Artist] AS [TARGET]
USING ( VALUES 

(N'Adrian Fisher', NULL, NULL, 1909, 2005),
(N'Alan Dun', NULL, N'http://www.kingbladudspigs.org', NULL, NULL),
(N'Alec Peever', N'Alec Peever has been designing and carving by hand since leaving art school in London in 1977.  His work can be found in most of England''s cathedrals, notably, St Paul''s, Winchester, and Westminster Abbey. Extract from Alec Peever’s page on ChurchArt: www.churchart.co.uk/findanartist', N'http://www.alecpeever.com', NULL, NULL),
(N'Alex Brogden', N'Born in 1954 Alex attended the Royal College of Art from 1979 to 1982 and trained with Leslie Durbin who also has a piece at Bath Abbey.Exhibiting internationally, in the Far East, across Europe and in America, his work is in many public and private collections. In Britain these include the Victoria and Albert Museum, The Crafts Council Collection, as well as the Silver Trust Collection for 10 Downing Street. He is currently silver advisor on the Modern Collection committee of the Goldsmiths Company whose collection of contemporary work is the largest in Britain.', N'http://www.alexbrogden.co.uk', 1954, NULL),
(N'Alex Ramsay', NULL, NULL, NULL, NULL),
(N'Alison Share', NULL, NULL, NULL, NULL),
(N'Alyson Hallett', N'Alyson Hallett grew up in Street, Somerset. She studied Comparative Literature at the University of East Anglia before going on to gain a distinction in her M.A. in Creative Writing from Bath Spa University. Since then she has consistently published poetry in magazines and journals, won competitions, received an Individual Artist’s Award from Arts Council England. Her first full volume, The Stone Library, has just come out with Peterloo Poets. Alyson has published short stories with Virago and Serpent''s Tail and her book, The Heart’s Elliptical Orbit (Solidus Press) was published in 2003. She has also written scripts for Sky Television and drama for Radio 4.  She teaches creative writing at Bristol University and co-teaches poetry with James Harpur at the Arvon Foundation. Alyson has a long-standing commitment to collaborating with other artists.', N'http://www.thestonelibrary.com', NULL, NULL),
(N'Ana Bilankov', N'Born in 1968 in Zagreb, Croatia, Ana lives and works in Berlin. Ana studied History of Art and German Language and Literature in Zagreb, Croatia and in Mainz, Germany. She graduated from the University of Zagreb. Studied Art Photography in Wiesbaden and completed postgraduate studies ''Fine Art in Context'' at the University of the Arts Berlin. She has realised her works in media such as photography, installation and video. She is one of the founders and members of Berlin based group ''Kunstcoop©'', which works on the borderline between art, art mediation, communication and research. She has exhibited in Croatia, Germany and UK.', N'http://anabilankov.com', 1968, NULL),
(N'Andrew Bolton', N'Andrew Bolton is a community and public artist with more than twenty years experience and an MA in Theory and Practice of Public Art and Design. His work ranges from small collaborative pieces in schools and community centres to large public work. Bolton’s work is site-specific, referring to local history and culture as well as the ideas and aspirations of the participants. It might refer to ancient/historic styles of art, for example, Roman mosaics, medieval floors or to more contemporary local issues.', N'http://communitymurals.org.uk', NULL, NULL),
(N'Andrew Edleston', NULL, NULL, NULL, NULL),
(N'Andrew Smith', N'Andrew Smith was born and educated in Kent.  He studied printmaking at Winchester School of Art.  He has recently moved from the study of interiors to focus on the landscape. Andrew Smith lives and works in Wiltshire.', NULL, NULL, NULL),
(N'Andy Croft', NULL, N'http://www.flambardpress.co.uk/books/show.php?book=1058&author=andy.croft', NULL, NULL),
(N'Angela Cockayne', N'Angela Cockayne did an MA in Visual Culture/Sculpture at Bath Spa University in 2000. In 2004 she exhibited ‘any day now…’at the Jerwood Space in London.', N'http://www.forgeprojects.co.uk/acindex.htm', NULL, NULL),
(N'Anita Andrews', N'Anita is a practicing visual artist, a community artist and qualified art teacher specialising in mosaic, mural painting, banners and festival arts. She has worked on large-scale projects as well as short workshops and particularly likes to assist groups to make work to enhance our environments. She encourages observational drawing and uses other mediums such as collage or print-making as part of the design process. She has worked extensively with pre-school groups, primary and secondary schools, youth clubs, special needs groups, families, adults including the over 60’s and the elderly in residential care homes. Anita also works on commissions.', N'http://www.anitaandrews.co.uk', NULL, NULL),
(N'Ann Scorgie', N'Ann Scorgie was born in 1941. She worked as a secretary then in publishing before studying at the University of Kent as a mature student between 1973-6. She developed MS in 1978, this both affected and informed her work. Scorgie attends the City of Bath College for painting classes and has exhibited at the College. She also took part in October 2004 in the show ''Creative Space'' at Holton Lea near Poole in Dorset. Scorgie also writes poetry and prose pieces for various writing groups.', N'http://www.bana-arts.co.uk', 1941, NULL),
(N'Anna Proctor', N'Anna Proctor is a Fine Art photographer and a Qualified Licentiate of the Master Photographers Association (LMPA) and a Licentiate of the Royal Photographic Society (LRPS). She works to commission for art, commercial and location lifestyle photographic work.', N'http://www.annaproctorphotography.co.uk', NULL, NULL),
(N'Anna Simmons', N'Anna has painted all her life, but she did not receive a formal training in her youth. In later life, after her children had left home, she gave up her job as a teacher to devote herself to painting. She then studied at St. Martin''s School of Art in London and this period inspired a particular direction in her work  which continues today. Anna has had one woman shows in London, Bath and America, and has sold widely all over the world, including Italy, Switzerland and Germany.', N'http://www.morganboyce-gallery.co.uk', NULL, NULL),
(N'Anne Egan', N'Anne attended Warwick University in 1980 before studying a Foundation course in Art and Design at the City of Bath College in 2003. She is currently doing a BA at Bath Spa University in the School of Art and Design. Anne has had several exhibitions at the Royal West of England Academy in Bristol. She also exhibited at the American Museum and at The Angel in London. She has worked collaboratively with children of St Mary’s Primary School in Bathwick, Bath.', NULL, 1959, NULL),
(N'Anthony Key', N'Born in South Africa from Chinese origin. At the age of 23 he moved to England where he has established himself as a leading artist, exploring the concept of cultural identity. Having gained a distinction for his MA at Brighton University, Anthony went on to complete his doctorship at the Winchester School of Art.', N'http://www.anthonykey.net', NULL, NULL),
(N'Arthur Goodwin', N'Vice Principal of Exeter College of Art and Design works to commission in mosaics. Examples of his work can be seen at Torbay Hospital, Northcott Theatre in Exeter and the Royal Devon and Exeter Hospital among several places. Other work can be found in private collections in England, the United States and India.', NULL, NULL, NULL),
(N'B. Holden', NULL, NULL, NULL, NULL),
(N'Barbara Ash', N'Since graduating from the Royal College of Art in 1995 Barbara has produced and exhibited work in England and abroad. She has been invited to participate in International Sculpture Symposiums around the world and was awarded the Henry Moore Fellowship from 1992- 1993. Throughout her career Barbara has undertaken both public & private commissions and her work appears in British and International collections.', N'http://www.barbaraash.co.uk', 1960, NULL),
(N'Barbara Davies', NULL, NULL, 1979, NULL),
(N'Barry Baldwin', N'Barry Baldwin was born in Staffordshire, he attended Stafford College of Art and Design and Bath Academy of Art. Thereafter his knowledge in the use of material for his work was acquired through a long apprenticeship in a broad range of stone carving and casting techniques. Working mostly in a public and monumental mode, his work can be seen in major cities in the United Kingdom and Europe, often as an integral part of an architectural scheme. Barry emigrated to the USA in 2001 and opened a gallery in the San Francisco Bay area.', N'http://www.baldwinsculptor.com', NULL, NULL),
(N'Bath Aqua Glass', NULL, NULL, NULL, NULL),
(N'Ben Gale', NULL, NULL, NULL, NULL),
(N'Ben Matthews', N'Born at the Chantry, Duston, Northampton in 1889, son of the Rev. B.Matthews. He trained and qualified as an architect before becoming a painter as a pupil of Eustace Frere and at the Architectural Association School in London. He went to Paris in 1923 and studied painting at the Academie Moderne under Othon Friesz and Fernand Leger. He lived and painted principally in France between the two World Wars.  From 1947 he spent a substantial amount of time in Spain and his work is mainly Mediterranean subjects. He was an Impressionist painter for many years but his work became more abstract from the 1970’s.Ben was also President of the National Society of Painters, Sculptors and Engravers and Honorary Secretary of the Royal Institute of Oil Painters. He exhibited not only in the UK but also in France, the United States and South Africa. Extract from a 1972 retrospective exhibition catalogue of Ben Matthew’s work at the Central Art Gallery in Northampton.', NULL, 1889, 1975),
(N'Bernard Adams', N'Bernard was a portrait and landscape painter. Born in London, the son of Robert Henry Adams, a painter and designer. He studied at Westminster School of Art, at the Antwerp Academy and with Philip de Laszlo, George Harcourt and Innes Fripp. He was a member of the Chelsea Arts Club and London Sketch Club. Exhibited at the Royal Academy, Chenil Galleries, Leicester Galleries and Paris Salon where he won a silver medal in 1957. He was elected Royal Painter in 1919 and a member of the Royal Oil Painters in 1923.', N'http://www.johnadamsfineart.com', 1915, 1965),
(N'Bobby Baker', N'Bobby Baker is one of Britain’s leading performance artists.She trained as a painter but soon found it hard to express her ideas in paint alone and turned instead to sugar and cake as more expressive media. She found that the best way of presenting these edible works of art to the public was through performance. In 1980 she had the first of her two children and in 1988 she first presented ‘Drawing on a Mother''s Experience’ telling the story of the intervening years and marking her come-back to performance art. Many new productions followed. ‘Cook Dems’ in 1990, the ‘Daily Life Series’ in 1991. In ‘Kitchen Show’, the first of the series, she opened her London kitchen to the public sharing with them her own domestic rituals.‘How To Shop’ followed in July 1993, and took the form of a lecture on the art of supermarket shopping,‘Take a Peek!’ was a fun fair where the grotesqueries of the stalls and side shows form Bobby Baker''s inimitable interpretation of the hilarities and humiliations, the sufferings and surrealism of a visit to the health centre. In Spring 2002, Baker began development of two new projects about the human mind ‘Voices Hearing’ and How to Live’, the latter became a production that premiered at the Barbican Theatre in November 2004 and toured the UK, including ICIA Arts Theatre at the University of Bath. Bobby Baker currently holds an AHRC Creative Fellowship in the English and Drama Department at Queen Mary, University of London. She also co-edited Redeeming Features of Daily Life (Routledge, 2007) with Professor Michèle Barrett, a retrospective of 35 years of Bobby’s career.', N'http://dailylifeltd.co.uk/about-us/people/daily-life-ltd-team/bobby-baker', NULL, NULL),
(N'Bronwyn Williams Ellis', NULL, NULL, NULL, NULL),
(N'Carlton Smith', NULL, NULL, NULL, NULL),
(N'Carolyne Kardia', N'Carolyne Kardia studied at St Martin''s School of Art and then the Royal College of Art in London, receiving an MA in sculpture in 1977. She also completed a postgraduate diploma in art and psychology at Hertfordshire College of Art. Her early work took the form of sculptural installation with cast components made in response to the architecture of particular gallery spaces. Painting became a central part of her practice once she began to work in colour. She continues to make site-specific sculpture, often in conjunction with two-dimensional work.', N'http://www.carolynekardia.co.uk', 1951, NULL),
(N'Chris Williams', N'Chris Williams has a BA in Furniture Design (1996) and an MA in Furniture Design and Technology (2006). He started exhibiting in 1996 at the London Business Centre as part of a new designer exhibition. In 2005 he exhibited in the Heavenly Bodies exhibition at the Herschel Museum in Bath. In 2008 he received the New Expression grant from the Museums, Libraries and Archives Council that led him to produce <i>Orrery</i> for the Herschel Museum. In 2009 he exhibited at the National Museum of Wales in Cardiff as part of the CAS Festival.', N'http://www.furniture4stargazers.co.uk', NULL, NULL),
(N'City of Bath college stained glass students', NULL, N'http://www.bathcollege.ac.uk/', NULL, NULL),
(N'City of Bath College stone mason students', NULL, N'http://www.bathcollege.ac.uk/', NULL, NULL),
(N'City of Bath College student sculptors', NULL, NULL, NULL, NULL),
(N'Cleo Mussi', N'Cleo is an established mosaic artist recognised in the applied  art world both nationally and internationally. She originally trained in Textiles at Goldsmiths before moving to mosaic work. In 2005 she collaborated with contemporary ceramicists to create ‘Unswept Floor 2005’ for the BBC in Leicester.', N'http://www.mussimosaics.co.uk', NULL, NULL),
(N'Colin Foster', NULL, NULL, NULL, NULL),
(N'David Backhouse', N'David Backhouse is a sculptor and a designer who lives and works near Bath. His early career was spent working and travelling in Europe, where he was particularly involved with portrait commissions. David has made many sculptures for public sites and private clients and has held numerous one-man exhibitions, both in the UK and abroad. He exhibits frequently at the Royal Academy Summer Exhibition and his work is in collections throughout the world. David is a Fellow of the Royal British Society of Sculptors (FRBS), a Royal West of England Academician (RWA), a Fellow of The Royal Society of Arts (FRSA) and a Member of The Society of Portrait Sculptors.', N'http://www.backhousesculptures.com', 1941, NULL),
(N'David Bowers', N'Since the summer of 2002 David has been working full time as a Community Mosaic Artist as part of Mosaic Madness, a business that provides mosaic workshops for schools, communities and corporate bodies. Before setting up Mosaic Madness, David was a Learning Disabilities Nurse for ten years.', N'http://www.mosaic-madness.co.uk', NULL, NULL),
(N'David Cox', N'Born in Bradford on Avon, David Cox was a pupil at Bath’s Art Secondary Modern and left with an A Level in art. He became a full time artist in 1979 and his first solo exhibition was held at the Artsite Gallery in Bath in 1981. Since then he has toured extensively and in 2001 was appointed WOMAD Festival’s visual artist. Extract from a press release for David Cox’ exhibition at the Victoria Art Gallery in 2005.', NULL, 1947, NULL),
(N'Davis, C.E.', N'Major C.E Davis was City Architect of Bath between 1862 and 1902.', NULL, 1862, 1902),
(N'Deborah Jones', N'Based in Bristol, Deborah Aguirre Jones has been working as an artist for over 20 years. Coming from a background of sculpture, in recent years she has become involved with research-oriented performances which contain encounters and exchanges with invited participants.', NULL, NULL, NULL),
(N'Deborah Robinson', N'Deborah was artist in residence at California State University Longbeach from 1996-7. In 2004 she completed a PhD in Fine Art practice, and in 2007 was artist in residence with Egenis, a multidisciplinary international group researching the impact of genomics on society based at the University of Exeter. Deborah has exhibited internationally, including the UK, America and Germany. She is a senior lecturer in painting/critical theory at the University of Plymouth.', N'http://www.bath.ac.uk/icia/archive/exhibitions07.shtml#robinson', NULL, NULL),
(N'Diana O’Keffe', NULL, NULL, NULL, NULL),
(N'Edith Massingham', NULL, NULL, NULL, NULL),
(N'Edwina Bridgeman', N'Edwina trained at Rose Bruford College of Speech & Drama in Kent and worked for many years as a scene painter in theatre. In 1990 she returned to college and did a BTEC in Art & Design at South Bristol. She started exhibiting in 1998 developed a solo show, ''All Saints'', for Black Swan Arts, Frome. She has since had solo exhibitions across the South West. In 2000 ''The Voyage Out'', a Black Swan Arts initiated project, toured the country until January 2003. In 2002 she received a major commission from the Royal United Hospital NHS Trust in Bath to create a piece for the atrium. In October 2003, she had a solo show at the Victoria Art Gallery, Bath entitled ‘Miracles''. Bridgeman also works with adults and children in workshops.', NULL, 1959, NULL),
(N'Eleanor Glover', NULL, NULL, NULL, NULL),
(N'Fiona Robinson', N'Fiona Robinson is an artist who works with paint and drawing media on canvas and paper.  She studied Fine Art and History of Art at Oxford Polytechnic in the 1980s and then went on to take an MA in Fine Art at the University of Portsmouth in 1997.  Line and the drawn mark are an intrinsic part of her work and she draws constantly, from observation and from memory, in her sketchbooks. She has exhibited in Open exhibitions in the UK and abroad from the early days of the Cheltenham Open Drawing Competition in 1998 (now The Jerwood Drawing Prize) through to Sketch 2005, The National Contemporary Drawing Open in 2005. In 2008 she was selected for the International Drawing Biennial in the Czech Republic.  She has always written, and has had features about other artists and reviews of exhibitions published in newspapers and national magazines.', N'http://www.fionarobinson.info', NULL, NULL),
(N'Fleur Kelly', NULL, NULL, NULL, NULL),
(N'George Lambourn', N'George Lambourn was a figure and landscape painter. Born 18 July 1900 in London he studied at Goldsmiths'' College, the Royal Academy Schools between 1924-1927, and in Paris. He served in H.M. Forces in both World Wars. He painted mainly in Cornwall and his first one-man exhibition was at the Matthiesen Gallery 1938.', NULL, 1900, 1977),
(N'Gilbert Randoll Coate', N'Coate was a British diplomat and a maze designer. Born in Lausanne, Switzerland, he won a scholarship to Oriel College, Oxford, reading French and German. In 1940 he worked for the Intelligence Corps and later joined the UK Foreign Office on various diplomatic postings after the war until 1967. Having had a long-standing interest in art and history, Coate took to designing mazes and completed over 50 new mazes in Britain and around the world. His first maze commission, The Imprint of Man, was completed in 1975 for a private garden in Gloucestershire. In 1979 he met Adrian Fisher and formed the maze design company Minotaur Designs. He died in Le Rouret, near Grasse, France aged 96.', N'http://www.en.wikipedia.org/wiki/Randoll_Coate', 1909, 2005),
(N'Graff’ project ', NULL, NULL, NULL, NULL),
(N'Helen Paris', N'Leslie Hill and Helen Paris formed their company Curious in 1996, they are artists who work in performance video and film. They have performed and exhibited widely in the UK, US, Europe, Australia and Asia.', NULL, NULL, NULL),
(N'Henry Haig', N'Henry Haig trained in painting and sculpture at Wimbledon School of Art between 1945 and 1950 and in Stained Glass at the Royal College of Art between 1952 and 1955. After five years teaching in schools, he opened a full-time studio. Since then he had completed more than 200 commissions. He has been a visiting tutor at several art colleges and an external degree assessor for the Glasgow School of Art. His commissions have included a window for Clifton Cathedral; a rose window for St Mary''s Swanage; an East window for St Stephen''s York, for All Saints, "Cathedral of the Forest", Newlands, Gloucestershire and Christ the King, Amesbury. He also has work in the Joseph Weld Hospice Chapel, Dorchester and twelve windows in Douai Abbey.', N'http://www.shaftesburycatholics.co.uk/Pages/StainedGlassWindow.html', NULL, 2007),
(N'Hetty Dupays', N'Hetty Dupays is the Arts Programme Manager at the Royal United Hospital in Bath. She studied at Bath Spa University and was awarded a BA and MA in Fine Art.', NULL, NULL, NULL),
(N'Hilary Cartmel', N'Hilary Cartmel studied at Exeter College of Art and Trent Polytechnic', NULL, NULL, NULL),
(N'Hugh D. Roberts', N'Roberts was a Councillor and Bath City Architect. He designed the prize winning Phoenix House Council flats in Julian Road, the National College of Domestic Sciences at Lansdown and the Kingsmead flat blocks built in 1961.  He was responsible for a large number of preservation schemes of Georgian buildings at the Circus and the Royal Crescent. He was also a Trustee of Bath Preservation Trust and a member of the Georgian Group.', NULL, NULL, NULL),
(N'Hugh Johnson', N'Hugh Johnson is still RNID Poolemead’s gardener', NULL, NULL, NULL),
(N'Ian Clegg', NULL, NULL, NULL, NULL),
(N'Igor Ustinov', N'Igor Ustinov is a sculptor living and working in Paris, the son of the celebrated actor Peter Ustinov. Igor studied sculpture under Cesar at the École Nationale Supérieure des Beaux Arts in Paris as well as biology at the university. His work can be seen at the French stock exchange in Paris, in St Petersburg alongside the work of the rest of this multi-talented family, or for a temporary exhibition ‘Ombres et Silhouettes’ at the top of the Arche de la Defense in Paris. Some of his work is part of the UBS art collection.', N'http://www.igorustinov.com', 1956, NULL),
(N'Ingrid Pollard', N'Born in Guyana, Ingrid lives and works in London. She studied Film and Video at the London College of Printing followed by an MA in Photographic Studies at the University of Derby. Ingrid has exhibited widely in Europe and America, including the National Portrait Gallery (London), Museum of Modern Art (Oxford), NGBK (Berlin), Caribbean Cultural Centre (New York) and Camerawork (San Francisco). Ingrid gained attention in the late 1980s with Pastoral Interlude, a series of photographs of black people in the English countryside. This was the start of an articulation of her experiences as a black British woman through the conventions of portraiture and landscape photography. Ingrid is now well known for exploring heritage, the romanticism of English landscape, and England''s hidden histories associated with Africa and the Caribbean.', NULL, NULL, NULL),
(N'Jacquie Binns', N'Jacquie Binns started creating artwork for the church in 1986 after spending 3 years studying at Goldsmiths Art College in London. Her embroidered work is free-hand machine embroidery and, amongst various techniques, ruching is employed to increase the play of light and texture on the surfaces. Around the world, the embroideries of Jacquie Binns are displayed in cathedrals, churches and private collections.', N'http://www.jacquiebinns.com', NULL, NULL),
(N'James Elliott', NULL, NULL, NULL, NULL),
(N'Jane Calow', N'Jane is a practising artist and writer with particular interest in commemoration, mourning, trauma and memory. Her PhD completed in 2003 at the University of Leeds explored trauma and artistic practice.Performed nationally and internationally, her recent artwork Traject explored the idea of a ''moveable site''. From 2000-2 she was Research Fellow at the Centre for Contextual Commemorative & Public Art at the University of the West of England, where she organised an international conference exploring commemoration, public representation and private mourning.  Jane teaches a unit on the MSc entitled ‘Death and the Arts’ at the University of Bath.', N'http://www.bath.ac.uk/cdas/people/cdasassociate/index.html#jc', NULL, NULL),
(N'Jane Lemon', N'Jane Lemon MBE is a founder member and Chairman of the Sarum Group, at Salisbury. She was a Costume Designer for B.B.C. Television for eight years, after more than five years experience in the theatre. After spending several years developing and teaching the art of embroidered box making, she has achieved her ambition of working entirely in ecclesiastical embroidery. Her designs may be seen in the Cathedrals of St Albans, Exeter, Salisbury and Wells, Bath and Sherborne Abbeys, and many churches around the country including two venues in the U.S.A.', N'http://www.practicalstudygroup.co.uk/members/jlemon/jlemon.html', NULL, NULL),
(N'Janos Kalmar', N'Janos Kalmar is Hungarian, he attended Warsaw and Budapest Academies of Art. Some of his work can be found at the British Museum collection.', NULL, NULL, NULL),
(N'Jeff Body', N'Jeff Body started his career in the printing industry and began looking for a new direction in life in his late thirties. He trained in stone carving with Laurence Tindall at Shute Farm Studio at Downhead and left the printing industry to become a sculptor in 1998. Nowadays he is involved in many carving in public sessions throughout the year and works with youth clubs and schools, usually sponsored by North East Somerset Arts (NESA). Jeff Body sculpts in stone, plaster and concrete, often using moulding and casting to create multiples and variations. He uses waste and industrial stone rather than art materials.', N'http://www.somerset-life.co.uk/the-magazine-somerset-art-and-antiques-art-for-the-people--93665', NULL, NULL),
(N'Jennie Gilling', N'Jennie Gilling’s background is in embroidery and textile design, which she studied at Canterbury and Croydon Art Colleges. She has been making paper since 1983. She is a founder member of PaperWEIGHT, the UK-based group of paper artists.  Jennie is also a professional gardener.Jennie’s early work in textiles emphasised surface decoration. She now manipulates the surface by using handmade paper from recycled sources and plant fibres. These are arranged into collages, often combined with embossed and cast pieces, calligraphy and further mixed media applied. She has been writing poetry for many years and often places text in her work because the extra layer words give to an image takes the viewer outside the frame. She has produced two limited edition artists'' books of poetry.', N'http://www.jenniegilling.co.uk', 1955, NULL),
(N'Jeremy Attrill', N'Jeremy Attrill graduated from Goldsmith University in 1987 with a BA in Textiles.', NULL, NULL, NULL),
(N'Jerry Ortmans', N'Jerry is a Bristol based artist. He trained at London College of Printing and started his career as a commercial printer. He later became a builder before turning to sculpture. An exhibition of his work at Spike Island Studios in Bristol in 2002 led to an Artist in Residence offer at Taurus in July 2003. He has exhibited at the Royal West of England Academy in Bristol, Winchester City Art Gallery and has installations at Ecole des Beaux Arts in Aix-en-Provence and in Zennor in Cornwall. Much of his sculpture is concerned with the idea of structure and the physical appearance of structure, commandeering different materials to work together. Jerry’s sculptures often appear precarious. He is keen to highlight and reflect on other social structures – especially the differences between the West and the Third World. All structures, whether in the form of religions, political groupings or more domestic arrangements, garner strength from the affiliation of their various parts. Any external influences might upset the equilibrium and are therefore viewed with suspicion.', NULL, NULL, NULL),
(N'Jill Watson', N'Jill Watson was brought up in Scotland. She trained as a sculptor at the Edinburgh College of Art and as a carver in Pietrasanta, Italy. Her work is generally figurative, and worked in marble or bronze. As well as significant public commissions, she has 30 years'' experience of private commissions and work for galleries around the world.', N'http://www.royal.gov.uk/output/page5210.asp', 1957, NULL),
(N'Jim Lowe', N'Jim Lowe, was elected a Fellow of the Royal Photographic Society in 2000, is Vice President of the Federation of European Photographers and Chairman of their qualifications board, Fellow and past president of the British Institute of Professional Photography and has had work published in the UK, Europe and the USA. His hand crafted black and white images have been acquired by collectors as far a field as Japan, India, South Africa, Canada and The Republic of Ireland as well as the UK and Europe. His work has been exhibited in London, Moscow and Bath. Jim also specialises in Architectural Photography, has recently published a book entitled ‘Architectural Photography Inside and Out’.', N'http://www.silvercontrast.com', NULL, NULL),
(N'Jim Partridge', N'Jim Partridge is a woodworker who studied woodturning at John Makepeace’s Parnham House School for Craftsmen in Wood and held a Fellowship at Crewe and Alsager College in Cheshire in 1984. In 1999 he was short-listed for the Jerwood Applied Arts Prize for Furniture. He has been working with Liz Walmesley since 1986. The partnership is responsible for the success of many architectural projects and environmental commissions including the Logpile Lookout at Kielder Forest and the shelter for Grizedale Forest. One of Partridge’s recent commissions was an altar and cross for Christ Church Cathedral in Oxford, using oak donated by Windsor Great Park. Jim and Liz’s work is in several collections including the V&A in London and Manchester Art Gallery.', N'http://www.culture24.org.uk/places+to+go/north+west/manchester/art19317', 1953, NULL),
(N'John Armstrong', N'John Armstrong born in 1937, trained as a painter and teacher at art schools in Swindon, Walthamstow and Brighton. Taught art and crafts in schools, worked in museums in Hove and Lewes, and at the Exhibitions Unit, University of Brighton Gallery.', N'http://www.armart.dircon.co.uk/john/rel-fig.html', 1937, NULL),
(N'John de Mears', NULL, NULL, NULL, NULL),
(N'John Morley', N'John studied at Beckenham School of Art between 1957 and 1962 before moving to the Ravensbourne College of Art and the Royal Academy Schools between 1963-1966. He exhibited across the UK throughout the 1980s including on several occasions in Bath and at the Royal Academy. In1990 he was elected Brother of the Art Workers Guild and became a Member of the Society of Wood Engravers for his engraving work. Morley paints the plants from his garden and the East Anglian landscape in which he has lived and worked for the past 30 years. He is very much part of the celebrated tradition of East Anglian painter-plantsman. The strength of his work lies in his combined knowledge of plants with mastery in conveying texture and the play of light on his subject. He returns time and time again to favourite subjects; the auricula paintings, red currants, flowerpots and snowdrops.', N'http://johnmorley.info', 1942, NULL),
(N'John Neilson', N'John studied calligraphy at Roehampton Institute, London, then worked for a year as assistant to Tom Perkins, returning to Wales in 1992. Most of his current work involves hand lettercarving in stone and slate, undertaken in the workshop or on site, and ranging from architectural lettering to memorials, plaques, and ''sculptural'' pieces. He is included on the Crafts Council index of selected makers and is a member of the Arts Council of Wales Crafts Advisory Panel. Recent clients include Memorials by Artists, Cumbria Arts in Education, Royal Collection Trust, The National Trust, Christ Church Cathedral, Oxford, and various local authorities and private clients.', N'www.letterexchange.org/members/68.html', 2007, NULL),
(N'John Packer', N'John Packer is a Bristol based artist/designer who has produced a broad range of public art and private commissions. His work is principally in metal, occasionally incorporating other media such as glass, stone and wood. Projects range from ''functional'' items such as railings and footbridges to kinetic and static sculptures. His pieces are usually site-specific.', N'http://www.johnpacker.com', NULL, NULL),
(N'John Potter', N'John began painting in various media over 45 years ago whilst living in Cornwall and subsequently studied at Falmouth School of Art. Much of his early work was abstract, though through an interest in the Impressionists, landscape and portraiture gradually came to the fore. In 1979 he began working in stained glass - attracted by the purity of colour and the concept of working directly with light. Initially he worked on a small scale producing ''light catchers'', continuing the themes pursued in his oil paintings. His work found financial success and he went on to work on larger projects for churches, schools, business premises and private individuals. After twenty years of working with stained glass Potter returned to painting. He is also a musician.', N'http://www.easelart.co.uk', NULL, NULL),
(N'Jonathan Cole', N'Jonathan Cole: artist, teacher and co-founder of Project Art Works, an organisation that creates opportunities for people with complex disabilities to make art. He was educated at St Olave''s grammar school in Orpington, Kent, and then studied fine art at Bristol Polytechnic. Graduating with a first-class degree he went on to the Royal Academy schools between 1986 and 1989 and won several scholarships and awards. In 1997 Jon and Kate Adams co-founded Project Art Works. In their work in schools for children with severe learning disabilities, they explored the use of materials and techniques to directly express form, movement and gesture. Most recently Jonathan’s compositions focused on trees simplified to skeletal, almost abstract signs.', N'http://www.guardian.co.uk/news/2007/may/03/guardianobituaries.artsobituaries', 1962, 2007),
(N'Julie Starks', N'Julie Starks has worked with a diverse range of client groups such as Greenpeace, The National Trust, Westonbirt Arboretum, Bath International Music Festival and Womad Festival as well as many Youth and Community groups across the UK. From 1998 she has been working in schools developing outdoor environments with living and dried willow structures and sculptures, in the South West and over the past three years in Scotland, Cumbria and Wales. Starks has also worked with adults teaching living and dried willow sculpture.', N'http://www.juliestarks.com', NULL, NULL),
(N'Juliet Hemingray', N'Juliet Hemingray first trained as an Art and Design teacher in Derby, England, 1974-1977. She was unsuccessful in securing a teaching post and spent the next few years mending clothes and making curtains, etc. It was in 1980 that a friend approached her to design and make an embroidered preaching scarf/tippet that he would wear at children''s services. Juliet’s work and business grew from strength to strength from then on.', N'http://www.church-textiles.co.uk', NULL, NULL),
(N'K. Fridrich', NULL, NULL, NULL, NULL),
(N'Katy Hallett', N'Katy is the founding member of Vizability Community Arts group in existence between 1988 and 1999. She became Sustrans Resident Artist and Arts Co-ordinator between 1989 and 2000 and has been Art Director on the Art & the Travelling Landscape project for the whole of the UK since 2000.', NULL, NULL, NULL),
(N'Kevin Clifford', NULL, NULL, NULL, NULL),
(N'Kevin Hughes', NULL, NULL, NULL, NULL),
(N'Kilda Meadows', N'Kilda is a Play Ranger at the Wansdyke Play Association. She is also a ceramic artist based in the South West.', NULL, NULL, NULL),
(N'Laurence Beckford', NULL, NULL, NULL, NULL),
(N'Laurence Tindall', N'Laurence Tindall specialises in Christian art and architecture. He trained as a sculptor at Kingston School of Art between 1969 and 1974. After graduating he worked as a stonemason and trained as a conservator at Wells Cathedral where he worked until 1984. Tindall became a lecturer in Sculpture at Bath Academy of Art from 1980 to 1990. In 1984 he joined the Partner Nimbus Conservation project, a group of conservators of historical buildings and monuments.', N'http://www.laurencetindall.co.uk', NULL, NULL),
(N'Lee Dickenson', N'Dickenson started working as a full time carver-sculptor in 1990 and has since been covering a range of works from architecture to furniture, ecclesiastical works, lettering, memorials, figures, wildlife sculptures, reproductions, restoration repair and conservation. He started running the Squashed Apple studio in Radstock in 1998, and is offering a full range of services. Some of his works have travelled as far as Europe, North America, India, the Far East and Australia.', N'http://www.squashedapplewoodcarving.co.uk', 1960, NULL),
(N'Lesley Kerman', N'Lesley is an artist who has been involved in several public art commissions. She has done a series of collages inserted in resin bricks for Sustrans cycle path at Nuneaton.', N'http://www.sustrans.org.uk/default.asp?sID=1122293089562', NULL, NULL),
(N'Leslie Durbin', N'Leslie Durbin is most well known for decorating the Sword of Honour, commissioned by King George VI in 1943 to honour the valiant conduct of the people of Stalingrad during the seven-month battle of 1942-43. Durbin studied silversmithing at the Central School of Arts and Crafts. By 1939 he won the second of his two awards from the Worshipful Company of Goldsmiths — a travelling scholarship, and shortly after started working on royal commissions at the workshop of his former Central School tutor Francis Adam. After the war Durbin entered into partnership with Leonard Moss sharing with him the workshop in Camden Town. In 1951 he was chosen to work with Professor Robert Goodden of the Royal College of Art on a tea service for the Festival of Britain. Connections with his early sponsors, the Worshipful Company of Goldsmiths, recurred over the decades. It was through the company’s recommendation that he won a commission from the Bank of England for an inkstand to commemorate its 250th anniversary in 1944. And in 1982 it was the company that staged the exhibition Leslie Durbin: Fifty Years of Silversmithing. Quitting his Camden Town workshop in his sixties, Durbin worked from home, making something of a second career with coin designs for the Royal Mint.', N'http://www.timesonline.co.uk/tol/comment/obituaries/article419362.ece', 1913, 2005),
(N'Leslie Hill', N'Leslie Hill and Helen Paris formed their company Curious in 1996, they are artists who work in performance video and film. They have performed and exhibited widely in the UK, US, Europe, Australia and Asia.', NULL, NULL, NULL),
(N'Liane Tancock', NULL, NULL, NULL, NULL),
(N'Lindy Clark', N'Lindy studied Fine Art at Bath Academy of Art and graduated in 1981.', NULL, 1956, NULL),
(N'Liz Fox', N'Liz Fox is a mosaic artist and a Keynsham resident who took part in the making of the Millennium Mosaic in Keynsham. After its completion she continued to practice mosaic with a group of local people and led the workshops to create the Keynsham Music Festival Mosaic. She teaches mosaic at Visage Arts Group, a community art group for the over 60’s in Keynsham.', NULL, NULL, NULL),
(N'Liz Walmsley', N'Liz’s work is in several collections including the V&A in London and Manchester Art Gallery.', N'http://www.culture24.org.uk/places+to+go/north+west/manchester/art19317', NULL, NULL),
(N'Local young people', NULL, NULL, NULL, NULL),
(N'M. Blow', NULL, NULL, NULL, NULL),
(N'M. Ford', NULL, NULL, NULL, NULL),
(N'Margaret Withers', N'Margaret Withers was an architect living in Bath who later moved to Cornwall.', NULL, NULL, NULL),
(N'Mark Angus', N'Born in Bath, Angus initially trained as a Chartered Surveyor but turned to architectural stained glass at the Swansea School of Art between 1976-1978. He now works in the UK and Germany and has created more than 300 windows for churches, cathedrals as well as for other public spaces and private houses since 1978. He has also been exhibiting extensively in Germany and Eastern Europe since 2000 and teaches master classes in stained glass. He has been visiting lecturer at the Royal College of Art London since 1980.', N'http://www.markangus.de', 1949, NULL),
(N'Martin Colbeck', N'Martin Colbeck''s love affair with elephants was first sparked back in 1994 when he was commissioned to fly to the Amboseli National Park in Kenya to photograph a family of elephants for David Attenborough''s ''Trials of Life'' TV series. Martin has been a wildlife photographer and filmmaker for more than 20 years. He has won the BBC Photographer of the Year, received two BAFTA and an Emmy nomination for cinematography. In 2006 he was nominated Wildlife Photographer of the year in the Nature in Black and White category. Colbeck has worked with David Attenborough on a number of projects, the latest being the BBC TV series ''Life of Mammals''.', N'http://www.martintrowbridge.com', NULL, NULL),
(N'Martin Fisher', N'Martin Fisher is an artist who became an architect. He designed this church window as well as the church itself. His other architectural works can be seen in Frome (St Catharine’s Church) and in Combe Down in Bath (St Peter and St Paul’s church).', NULL, 1930, NULL),
(N'Martyn Ware', N'Illustrious and Martyn Ware - The Illustrious Company was formed in 2001 to create new forms of spatialised sound composition using their unique three-dimensional 3D AudioScape surround-sound system, in particular for collaborative works with digital and fine artists, museums, exhibitions, live events, dance, theatre, and education.', N'http://www.illustriouscompany.co.uk', 1956, NULL),
(N'Matthew Body', NULL, NULL, NULL, NULL),
(N'Mel Day', N'Mel Day is an artist interested in transformation. She makes pieces out of wire that centre around the natural world. She has exhibited at Frome Festival and the New Brewery Arts in Cirencester. Mel also runs workshops across the South West and in particular at Black Swan Arts in Frome. She has been regularly commissioned to work with school children in B&NES to produce artworks for the children’s parade for the opening of Bath International Music Festival', NULL, NULL, NULL),
(N'Melanie Sproat', N'Melanie graduated with an MA in Applied Art-Fine Metals at the Royal College of Art in 1978 following a BA in 3D Design (wood, ceramics, metal and glass) at Buckinghamshire College of High Education. Between 1980 and 2000 she was a freelance designer and maker of 3D works and a teacher of 3D design. She is currently course leader in jewellery and fine metal at the City of Bath College. She worked on several commissions including for Durham Cathedral, HRH The Duke of Gloucester, Clerical Medical Investment Group and National Westminster Bank Narrow Quay Development in Bristol. She is a member of the British Artist Blacksmith Association and the Association of Contemporary Jewellers.', NULL, NULL, NULL),
(N'Meryl Stannard', N'Meryl trained as a ballet dancer but an injury curtailed her career and she retrained in stained glass between 1976-1978 at the Central School of Arts. She has been teaching stained glass since 1981 in London and the South West. Examples of her work can be seen in permanent collections at Kew and the University of Bath.', NULL, NULL, NULL),
(N'Michael Fairfax', N'Michael is a sculptor who graduated from Portsmouth Art College in 1979 and went on to study at Newport Gwent in 1980. He settled in Berkshire where nature was a constant source of inspiration, seeking in his work to create a visual coherence with the environment. He turned his attention to sculpture trails and was commissioned by arts organisations and county councils across the UK. He has also created garden, interior and poem pieces and was Lead Artist on the Heavitree improvement projects in Exeter (September 2007 -2008) and currently on the Blackdown Hills Ridge Route Project 2005 -06, extended to 2009. He now lives in Somerset with his family.', N'http://www.michaelfairfax.co.uk', 1953, NULL),
(N'Michael Pennie', N'Michael Pennie is a sculptor whose work is usually made by carving wood. Since 1960 he has had numerous solo shows, his first at the ICA, and later group shows at Tate Britain, the Serpentine and Hayward Galleries and Yorkshire Sculpture Park.Pennie is particularly interested in African art and inspired by the work of the Lobi people of the Upper West region of Ghana whom he visited extensively. This led to the curation of three touring exhibitions in this part of the world. Pennie was also Senior Lecturer in sculpture at the Faculty of Art and Music at Bath Spa University and then Professor from 1996 until his retirement from teaching in 2001. Since then Pennie has placed his large sculpture Assembly inside the Cathedral at Salisbury as part of the In Praise of Wood exhibition. In September 2004 he began his Project of 100 Small Bronzes cast and toured the South West.', N'http://www.michaelpennie.net', NULL, NULL),
(N'Mike Burrows', N'Mike Burrows is a local poet.', NULL, NULL, NULL),
(N'N. Rose', NULL, NULL, NULL, NULL),
(N'Neal Tanner Partnership', N'Architects of St Andrews’ School', NULL, NULL, NULL),
(N'Nick Lowe', NULL, NULL, NULL, NULL),
(N'Nigel Bryant', N'Nigel Bryant is a City of Bath College Stonemasonary Lecturer, an artist and a Sustrans Ranger. He was a member of the Two Tunnels cycling scheme project for which the King Bladud’s Pigs in Bath raised money', NULL, NULL, NULL),
(N'Nigel Keegan', NULL, NULL, NULL, NULL),
(N'Olga Lehmann', N'Olga Lehmann was a visual artist born in Chile. Educated at Santiago College she moved to England in 1929 when she was awarded a scholarship at the Slade School of Fine Art. She specialised in theatrical design under Vladimir Polunin and in portraiture under Alan Gwynne-Jones. Awarded prizes in Life Painting, Composition, and Theatrical Design, she visited Spain in the early Thirties; Spanish and Moorish themes were subsequently reflected in her work. Throughout the 1930s she acquired a reputation in the fields of mural painting and portraiture. She exhibited her work at the Royal Portrait Society in 1933, and with the London Group in 1935. During World War II she painted murals for the London Air Raid Precautions (ARP) Headquarters and the Censorship Department in Holborn. She was also allowed to draw bomb damage, air raid shelters, and ARP personnel in London. After World War II, her name chiefly became associated with graphic design for the Radio Times and design for the film and television industries.', N'http://en.wikipedia.org/wiki/Olga_Lehmann', 1912, 2001),
(N'P. Jennings', NULL, NULL, NULL, NULL),
(N'Pat Panton', NULL, NULL, NULL, NULL),
(N'Patricia Laing', NULL, NULL, NULL, NULL),
(N'Paul Cresswell', NULL, NULL, NULL, NULL),
(N'Paul Fletcher', N'Paul Fletcher trained at Goldsmith''s College and the Royal College of Art.  He has spent a lifetime working at sculpture. In 2005 he was given the Jean Masson Davidson Medal by the Society of Portrait Sculptors. His work can be seen in private collections in Britain, USA, Canada, Australia, France, Cyprus.', N'http://www.churchart.co.uk/findanartist/viewArtist.php?artistID=100', NULL, NULL),
(N'Peter John Wells', N'Born in Eldoret, Kenya, Peter attended the Bath Academy of Art between 1977 and 1980. He subsequently exhibited in London, Brussels and with The British Council in India  in 1996, 2000 and 2007. In 1999 he was nominated Guardian Artist of the month. Peter has also illustrated children’s books for Action Aid and has designed sets for the Opera Director Ian Burton. Peter spends six months of the year travelling in India and creates many of his pieces while he is there, other work he recreates at home in England in the summer, working from pencil sketches, pen and ink drawings, photographs, entries in his journals. He presented another <i>RE: cycle</i> sculpture at Glastonbury Festival in 2007.', N'http://www.peterjohnwells.co.uk', 1958, NULL),
(N'Peter Linnett', NULL, NULL, NULL, NULL),
(N'Peter Logan', N'Peter Logan has made kinetic sculpture since leaving the Slade School London. Early works between1969-79 were rigorously composed performances of electronic, mechanical ballets, programmed to repeat each performance as composed. At first these were exhibited in interior spaces and later in outdoor locations. While working outdoors alongside nature Logan developed from 1975 his wind energised sculptures. These sculptures began exploring random performance in extensive time frames across the seasons as with Nails.', N'http://www.peter-logan.com', 1943, NULL),
(N'Peter McLennan', NULL, NULL, NULL, NULL),
(N'Peter Osborne', N'Born and educated in Cambridge, Peter developed a strong interest in architecture, and after spending time travelling through North Africa and Central Asia, he worked independently for eighteen years in building conservation, specialising in structural repairs. Architectural ironwork became a particular interest, and between 1988 and 1995 Peter trained in blacksmithing and set up his own forge. He now works from a forge and studio in Somerset, where alongside traditional blacksmithing and conservation work, he also produces both functional and sculptural pieces, for architectural and landscape/garden projects, as well as undertaking commissions for larger site specific work -often public and Community Arts work. Peter uses natural forms as the basis for design, and is particularly interested in combining metals with other media - mortars, glass, mosaic, light, water etc. The organic forms make his work accessible, whilst challenging the public perception of the materials, and their more traditional forms and uses.', N'http://www.peterosborne.co.uk', NULL, NULL),
(N'Peter Wright', N'Peter attended Hornsey College of Art from 1946 to 1950 where he studied graphics, but also discovered clay. In 1957 he went to teach art at Sutton Coldfield college of further education, where he was obliged to also take ceramics classes. A crash course of self-tuition refocused his interest in the material and its possibilities. He realised how he could integrate his graphic skills with a three-dimensional form and was attracted to a discipline with its own seductive alchemy and processes. In 1954 he settled down with his wife Sheila at Monkton Combe near Bath and made a living producing well-designed domestic ware but also ambitious press-moulded tin glaze pieces that reflected the structure of the surrounding landscape. Successful with this work, Wright exhibited at venues like the British Crafts Centre, the Design Centre and, in 1957, at the Victoria and Albert Museum. Despite his admiration for Minoan and Cycladic pottery, Wright distanced himself from most contemporary ceramics and looked to a broader picture - to medieval art, African sculpture and artists such as Chagall and Morandi. In 1957 he began teaching at Bath Academy of Art and then at the college of education. By the mid-1960s he became frustrated by creative stasis, and moved in a more sculptural direction. He made inventive abstract pieces, notably in porcelain. His underlying themes dealt now with issues of unity and integration, separation and release. By the late 1970s, though still making some pots and producing relief pieces, his activity centred on the small figurative interlocking sculptures for which he is best known.', N'http://www.guardian.co.uk/news/2003/aug/25/guardianobituaries.artsobituaries1', 1919, 2003),
(N'Piers Ottey', N'Born in London, Piers trained at Chelsea School of Art in the 1970s. He has been painting ever since. He moved to West Sussex in 1980 and set up The Mill Studio in 1994. Painting mostly in oils, his subject matter has often been influenced by his travels to Greece, Spain, France and Denmark but he always returns to painting from the human form. He paints landscapes, objects as well as semi-abstract forms. His work has been exhibited in London, the provinces and abroad and can be found in private and corporate as well as public collections around the world.', N'http://www.piersottey.co.uk', NULL, NULL),
(N'Queens Road Cru', NULL, NULL, NULL, NULL),
(N'Quintin Howard Evans', NULL, NULL, NULL, NULL),
(N'Ray Smith', N'Ray Smith was Lead Artist for the Bristol Royal Hospital for Children between 1997-2001 and in 2006 Lead Artist for the New Hospitals Development in Central Manchester. Ray has made many large-scale exterior works, including the painted steel sculpture, <i>Red Army</i> (1990) in Pennsylvania USA, the fibre-optic lighting artwork <i>Making Waves</i> (1999), in Teignmouth, Devon and the water-jet cut stone sculpture <i>On a Roll</i> (2005), in Hamble, Hampshire. In 2006 he installed a 32 metres laminate wall artwork in Emsworth, Hampshire and a series of hand-printed laminate artworks for Southmead Hospital in Bristol (2006). Temporary installations include the trompe l’oeil planting artwork, <i>Autumn leaves Summer 96</i> (1996) in County Durham and <i>At Full Stretch</i> (2003), an exterior vinyl artwork over the 30 floors of the Trellick Tower in West London.', N'http://www.raysmithartist.com', NULL, NULL),
(N'Rebecca Yeo', NULL, NULL, NULL, NULL),
(N'Richard Cooper', NULL, NULL, NULL, NULL),
(N'Richard Long', N'Born in Bristol, Richard studied at the West of England College of Art, Bristol between 1962-5 and then St. Martin''s School of Art, London between 1966-8. He lives and works in Bristol and has an international career in landscape sculptures. He was nominated four times for the Turner Prize and has been exhibiting in the most prominent museums and galleries since 1968, from the Museum of Modern Art in New York, to the Whitechapel Art Gallery in London and the Setagaya Art Museum in Tokyo.', N'http://www.richardlong.org', 1945, NULL),
(N'Richard Sadd', N'Richard Sadd organised arts and craft sessions for Poolemead residents and later became a Sign Language interpreter.', NULL, NULL, NULL),
(N'Robert Race', N'Robert Race has been a toy maker since the late 1970’s Starting with dolls’ houses and miniature furniture he has subsequently concentrated on moving toys and simple automata, which have been widely exhibited in Britain, Europe and beyond. Since 1991 he has been an active member of the British Toymakers Guild, and was Chairman from 2003 to 2006. In September 2005 he appeared at Expo 2005 Aichi, Japan as a specially invited guest of the World Karakuri Contest. Commissions have included Exhibition design for Transformations-the Art of Recycling at the Pitt Rivers Museum, Oxford (March 2000-Sept 2002), a collection of Victorian optical toys for Sutton House, Hackney (National Trust), and mechanical donation boxes for Black Swan Arts, Frome; Salisbury Playhouse and Dorset County Hospital in Dorchester.', N'http://www.robertrace.co.uk', NULL, NULL),
(N'Ros Ford', N'Ros Ford is a painter and printmaker. She received an MA in fine art printmaking Chelsea Art school 1975. She lived in Egypt 1989 - 1995 working as an artist in development projects. She now lives and works in Bristol. Her work is in public collections in the UK and Egypt and private collections in the UK, Europe, Egypt and USA.', NULL, NULL, NULL),
(N'Rosalind Waites', N'Rosalind Waites is an artist who specialises in mosaic. Her work covers a wide spectrum of styles, material and techniques. She works mainly to commission for private clients, public bodies, art organisations, schools and communities. She uses glass, ceramic, marble, slate, gold and natural stone. As well as producing mosaics she also teaches and writes on the subject.', N'http://www.mosaicmatters.co.uk/features/wates.htm', NULL, NULL),
(N'Rose Flint', N'Rose Flint is a poet and art therapist. She teaches Creative Writing for Therapeutic Purposes at Bristol University. Her work has ranged from a music collaboration writing Oratorios from the Mabinogion in four Welsh primary schools to co-tutoring Writing and Spirituality, and Poetry and Healing courses at Ty Newydd. A prize-winning writer, she has received awards from both Arts Council England and from the Poetry Society. Her first two collections are Blue Horse of Morning (Seren, 1992) and Nekyia (Stride, 2003). In 2008 Flint won Academi Cardiff International Poetry Competition. Now living in Bath, Flint spent many years on the Welsh Borders, an experience which continually threads through her creative work.', N'http://www.poetrysalzburg.com', NULL, NULL),
(N'Roz Moorehouse', N'Roz Moorehouse is an artist and a former nurse.', NULL, NULL, NULL),
(N'Ruth Moilliet', N'Ruth Moilliet has an established reputation for sculpting glass and metal. Her work explores the strength of nature and its ability for survival.Ruth was awarded a BA in Fine Art Sculpture in 2000 and an MA in Art as Environment from Manchester Metropolitan University in 2002.  She has had a range of collective and solo exhibitions across the UK since 2002. She was commissioned by Kew Gardens, the Botanic Garden of Wales, Urban Splash and internationally by the Four Seasons Hotel in Hong Kong.  Her works regularly appears in the national press, garden and interior decoration magazines. ', N'http://www.ruthmoilliet.com ', NULL, NULL),
(N'Sarah Wilson', N'Sarah was a student at the City of Bath College', NULL, NULL, NULL),
(N'Sebastian Boyesen', N'Sebastian is a sculptor who has produced several public sculptures in bronze around the UK.  He was Newport Town Sculptor between 1993 and 1994. He also produced tiles for a Bristol underbridge on the Bristol to Bath cycle path and a mosaic in the city centre of Wigan.', NULL, NULL, NULL),
(N'Sophie Ryder', N'Sophie Ryder is figurative artist renowned for her giant sculptures exploring mythical characters and more particularly her own creation of the Lady-Hare, part human, part hare, a figure she has developed over the years. She trained in sculpture at the Royal Academy School between 1981-1984 and was involved in many site-specific projects across the UK including the Forest of Dean. She has exhibited nationally and internationally, across Bath in 1999 and lately at the Yorkshire Sculpture Park.', N'http://www.sophieryder.org', 1963, NULL),
(N'Sophie White', N'Sophie White is a professional Bristol sculptor exhibiting throughout the U.K in sculpture parks and galleries. Her life-size and smaller works capture fleeting moments of human interaction. Her work is cast in bronze and bronze-resin. White followed her passion for creating sculpture after graduating with a language degree at Nottingham University and studied at the Elizabeth Frink School of Sculpture in Staffordshire followed by a postgraduate course at The Cyprus College of Art. The artist returned to the U.K in 2001 and set up her studio at Spike Island in Bristol and later at Widcombe Studios in Bath. She has had ten solo shows including at the Grant Bradley Galley in Bristol, Kingswood School in Bath (where she was artist in residence), Brixton Art Gallery in London and Broomhill Sculpture Park in Devon.', N'http://www.axsf41.dsl.pipex.com/index.htm', NULL, NULL),
(N'Stefano Valerio Pieroni', N'Little is known about Stefano Valerio Pieroni . He was an Italian sculptor who also produced a large Bath stone basin, the Kemble Vase, that he donated to the Royal Victoria Park in the middle of 19th C.Nigel Bryant is a City of Bath College Stonemasonary Lecturer, an artist and a Sustrans Ranger. He was a member of the Two Tunnels cycling scheme project for which the <i>King Bladud’s Pigs in Bath</i> raised money.', NULL, NULL, NULL),
(N'Stephen Budd', N'Stephen Budd is Bath based cabinet-maker and is workshop manager at Wood Works, a Genesis Trust project in Bath that offers placements to the long term unemployed who repair and refurbish furniture donated to them by the general public.', NULL, NULL, NULL),
(N'Stephen Gill', N'At an early age, Stephen was introduced to photography by his father. He built on this early interest by working part-time for a local photographer while still at school, restoring old photographs and helping to take family portraits. After leaving school at 16 he worked full-time in a one-hour photo lab in the city before enrolling in 1992 on a Photography foundation course at Bristol''s Filton College. Stephen''s photographs are now held in various collections worldwide. They have also been exhibited at many international galleries, festivals and museums including the Victoria and Albert Museum, the National Portrait Gallery and The Photographers'' Gallery in London, Victoria Miro Gallery, Palais des Beaux Arts in Brussels and Rencontres d''Arles in Arles, Munich''s Haus Der Kunst, and Photo España in Madrid.', N'http://www.stephengill.co.uk', 1971, NULL),
(N'Stephen Magrath', N'Stephen Magrath is a Fine Art Bath Spa graduate (2007) The theme of his practice reflects a fascination with human microbiology, imagery invisible to the naked eye but detected via modern photographic technology. He is particularly drawn to recent electron microscopic images of topical viruses like HIV and ‘bird flu’ or threatening bacteria like E-coli.', N'http://www.stephenmagrath.co.uk', NULL, NULL),
(N'Steve Porter', N'Steve Porter is an artist and a musician who has worked extensively in schools in the South West region.  Alongside the children he has produced murals, decorated furniture and collages. His sculpture <i>Lump Sum</i> was temporarily exhibited outside the Bank of England’s building in London.', N'http://www.steveporter.org', NULL, NULL),
(N'Sue Symons', N'Sue is an artist from Peasedown St John. She studied hand-drawn lettering at Bath Academy of Arts and chose decorative needlework in the 1960’s while studying at Leicester College of Art.', NULL, NULL, NULL),
(N'The Sarum Group', N'The Sarum Group was founded in 1978 when Jane Lemon’s class was invited by the Dean of Salisbury Cathedral to mount an exhibition of their ecclesiastical embroidery. From then on the group received many commissions.', NULL, NULL, NULL),
(N'Tim Horriga', NULL, NULL, NULL, NULL),
(N'Tony Hay', N'Tony Hay organised music and movement sessions for residents at RNID Poolemead.', NULL, NULL, NULL),
(N'Vivien Mousdell', N'Originally trained as a ceramist and a stone carver, Vivien Mousdell is a sculptor, a puppeteer and an installation artist. Her background is as a site-specific sculptor with public commissions throughout the North of England. She continues to work in response to people and place in her current practice that integrates installation and performance.Preferring to work across creative boundaries and uniting her interest in movement with that of sculpture, she studied with the London School of Puppetry to become a professional puppeteer.As a Northern Arts Fellow with Welfare State International she began to develop site sensitive performance, and subsequently received an Arts Council research and development award to explore the interface between installation and animation ‘Puppets in Place’. Most recently she developed an ambitious three-dimensional video and sound installation ‘Waves’ for the Centre for Performance Research. Vivien is also part of collective of artists called Dome D’ombre that creates shadow theatre and light installations. The collective is based in Whitby, North Yorkshire.', N'http://www.domedombre.com/vivienmousdell.html', NULL, NULL),
(N'Vizability Community Art', N'Vizability was an artist led co-operative based in Bishopston in Bristol. They ceased to exist after Avon County became unitary authorities.', NULL, NULL, NULL),
(N'William Pye', N'William Pye studied at Wimbledon School of Art (1958-61) and at the Sculpture School of the Royal College of Art (1961-65). His sculptures of the 1960s were abstract forms and showed Pye’s preference for the traditional materials of metal and stone. Highly polished geometrical works in stainless steel of the 1970s, some of which included elements of movement, reflection and the use of light, led him logically to consider water as an essential part of his artistic expression. The natural world that he explores in his sculptures is interpreted through water, metal and stone, where disarmingly simple concepts become the objects of utmost sophistication. Early stainless steel sculptures such as Narcissus 1969 and Quillion 1970 are lyrical expressions of form, rhythm, movement and reflection. They both herald William Pye’s move towards using stainless steel in combination with water. The contrast between straight and rolling forms, geometrical and organic are also preludes to everything that emerges later in Pye’s work when water is combined.', N'http://www.williampye.com', 1938, NULL),
(N'Yannick Li Ah Kane', N'Born in France and trained in historical monument restoration, Yannick began his career restoring buildings, castles, fountains and houses across France. He eventually set up his own business ‘L’Atelier du Geai de Pierre’ in 2006 and became increasingly interested in making sculpture. In 2007 he won first prize at the Candelon Symposium (a pink marble competition) and trained to sculpt white marble in Carrara, Italy. He moved to Bath in 2008 and set up a workshop dedicating his time to sculpture making.  In 2009 he carved ‘Man is Only Dust’ during Bath Fringe Festival. The sculpture is now at the Mythic Garden in Devon.', N'http://www.YKSculpture.com', 1979, NULL),
(N'Yumiko Aoyagi', N'Yumiko Aoyagi was a student in Furniture Design at Rycotewood College in Thame in Oxfordshire in 2002 when she designed Simplicity Bench. She worked with lead artist Angus Ross to produce it for the Phoenix cycle path between Thame and Princes Risborough.', NULL, NULL, NULL)

) AS [SOURCE] (
    [Name]
,   [Biography]
,   [WebsiteURL]
,   [StartYear]
,   [EndYear]
)
ON [TARGET].[Name] = [SOURCE].[Name]

WHEN NOT MATCHED BY TARGET THEN
    INSERT (    
        [Name]
    ,   [Biography]
    ,   [WebsiteURL]
    ,   [StartYear]
    ,   [EndYear]  
    )
    VALUES (
        [SOURCE].[Name]
    ,   [SOURCE].[Biography]
    ,   [SOURCE].[WebsiteURL]
    ,   [SOURCE].[StartYear]
    ,   [SOURCE].[EndYear]
    )
WHEN MATCHED
AND NOT EXISTS ( SELECT
                    [SOURCE].[Name]
                ,   [SOURCE].[Biography]
                ,   [SOURCE].[WebsiteURL]
                ,   [SOURCE].[StartYear]
                ,   [SOURCE].[EndYear]
                 INTERSECT
                 SELECT
                    [TARGET].[Name]
                ,   [TARGET].[Biography]
                ,   [TARGET].[WebsiteURL]
                ,   [TARGET].[StartYear]
                ,   [TARGET].[EndYear]
    ) THEN UPDATE SET
        [Name]          = [SOURCE].[Name]              
    ,   [Biography]     = [SOURCE].[Biography]        
    ,   [WebsiteURL]    = [SOURCE].[WebsiteURL]               
    ,   [StartYear]     = [SOURCE].[StartYear]      
    ,   [EndYear]       = [SOURCE].[EndYear]   
    ,   [ModifiedDate]  = CURRENT_TIMESTAMP;

RETURN 0;