//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicArt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageThumbnail
    {
        public System.Guid stream_id { get; set; }
        public byte[] file_stream { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
