//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicArt.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PublicArtEntities : DbContext
    {
        public PublicArtEntities()
            : base("name=PublicArtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ImageThumbnail> ImageThumbnails { get; set; }
        public virtual DbSet<ItemArtist> ItemArtists { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Item> Items { get; set; }
    
        public virtual int SetPrimaryItemImage(Nullable<int> itemId, Nullable<System.Guid> stream_id)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("itemId", itemId) :
                new ObjectParameter("itemId", typeof(int));
    
            var stream_idParameter = stream_id.HasValue ?
                new ObjectParameter("stream_id", stream_id) :
                new ObjectParameter("stream_id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetPrimaryItemImage", itemIdParameter, stream_idParameter);
        }
    }
}
